#! /bin/bash
#
# This entrypoint script will be called every time a container is started.
#
# Author: Kaj Munhoz Arfvidsson

set -e

# Get project information
source util/config.sh

# Set ROS_IP etc. for e.g., RViz remote connection
# https://stackoverflow.com/a/65912397
remote_ros() { source util/remote_ros.sh; }; remote_ros

# Build the ROS2 workspace if files have been added or modified by volume
if [ -d "$WORKSPACE/src" ]; then
    echo "Building the ROS2 workspace..."
    . /opt/ros/$ROSDISTRO/setup.bash
    colcon build --symlink-install --base-paths "$WORKSPACE"
fi

# Source the ROS2 workspace setup file
if [ -f "$WORKSPACE/install/setup.bash" ]; then
    printf "\nsource '$WORKSPACE/install/setup.bash'" >> $HOME/.bashrc
    . "$WORKSPACE/install/setup.bash"
fi

# Execute the container's command
exec "$@"
